### ISSUE TITLE
[FEATURE] Add docker support

### ISSUE THREAD

**Issue by guibranco** [andersson601sp/ContaDigital#2]
Add a DockerFile and a docker-compose.yml file to the project, so it will make it easy to build & test in any environment.

Also, add [user-secrets](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows) to solution, making easy to store connection strings and other tokens.

**Comment by andersson601sp** [comment]
Done
